//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.10 at 10:39:31 AM EET 
//


package uk.ac.aber.simsphere;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SurfaceMoistureAvail" type="{http://aber.ac.uk/simsphere}HydrologicalParamsType"/>
 *         &lt;element name="RootZoneMoistureAvail" type="{http://aber.ac.uk/simsphere}HydrologicalParamsType"/>
 *         &lt;element name="SubstrateMaxVolWaterContent" type="{http://aber.ac.uk/simsphere}HydrologicalParamsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "surfaceMoistureAvail",
    "rootZoneMoistureAvail",
    "substrateMaxVolWaterContent"
})
@XmlRootElement(name = "HydrologicalParams")
public class HydrologicalParams {

    @XmlElement(name = "SurfaceMoistureAvail")
    protected float surfaceMoistureAvail;
    @XmlElement(name = "RootZoneMoistureAvail")
    protected float rootZoneMoistureAvail;
    @XmlElement(name = "SubstrateMaxVolWaterContent")
    protected float substrateMaxVolWaterContent;

    /**
     * Gets the value of the surfaceMoistureAvail property.
     * 
     */
    public float getSurfaceMoistureAvail() {
        return surfaceMoistureAvail;
    }

    /**
     * Sets the value of the surfaceMoistureAvail property.
     * 
     */
    public void setSurfaceMoistureAvail(float value) {
        this.surfaceMoistureAvail = value;
    }

    /**
     * Gets the value of the rootZoneMoistureAvail property.
     * 
     */
    public float getRootZoneMoistureAvail() {
        return rootZoneMoistureAvail;
    }

    /**
     * Sets the value of the rootZoneMoistureAvail property.
     * 
     */
    public void setRootZoneMoistureAvail(float value) {
        this.rootZoneMoistureAvail = value;
    }

    /**
     * Gets the value of the substrateMaxVolWaterContent property.
     * 
     */
    public float getSubstrateMaxVolWaterContent() {
        return substrateMaxVolWaterContent;
    }

    /**
     * Sets the value of the substrateMaxVolWaterContent property.
     * 
     */
    public void setSubstrateMaxVolWaterContent(float value) {
        this.substrateMaxVolWaterContent = value;
    }

}
