//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.10 at 10:39:31 AM EET 
//


package uk.ac.aber.simsphere;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://aber.ac.uk/simsphere}AtmosphericPrecipitableWater"/>
 *         &lt;element ref="{http://aber.ac.uk/simsphere}SurfaceRoughness"/>
 *         &lt;element ref="{http://aber.ac.uk/simsphere}ObstacleHeight"/>
 *         &lt;element ref="{http://aber.ac.uk/simsphere}CloudFract"/>
 *         &lt;element ref="{http://aber.ac.uk/simsphere}UseCloudCover"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "atmosphericPrecipitableWater",
    "surfaceRoughness",
    "obstacleHeight",
    "cloudFract",
    "useCloudCover"
})
@XmlRootElement(name = "Meteorological")
public class Meteorological {

    @XmlElement(name = "AtmosphericPrecipitableWater")
    protected float atmosphericPrecipitableWater;
    @XmlElement(name = "SurfaceRoughness")
    protected float surfaceRoughness;
    @XmlElement(name = "ObstacleHeight")
    protected float obstacleHeight;
    @XmlElement(name = "CloudFract")
    protected float cloudFract;
    @XmlElement(name = "UseCloudCover")
    protected boolean useCloudCover;

    /**
     * Gets the value of the atmosphericPrecipitableWater property.
     * 
     */
    public float getAtmosphericPrecipitableWater() {
        return atmosphericPrecipitableWater;
    }

    /**
     * Sets the value of the atmosphericPrecipitableWater property.
     * 
     */
    public void setAtmosphericPrecipitableWater(float value) {
        this.atmosphericPrecipitableWater = value;
    }

    /**
     * Gets the value of the surfaceRoughness property.
     * 
     */
    public float getSurfaceRoughness() {
        return surfaceRoughness;
    }

    /**
     * Sets the value of the surfaceRoughness property.
     * 
     */
    public void setSurfaceRoughness(float value) {
        this.surfaceRoughness = value;
    }

    /**
     * Gets the value of the obstacleHeight property.
     * 
     */
    public float getObstacleHeight() {
        return obstacleHeight;
    }

    /**
     * Sets the value of the obstacleHeight property.
     * 
     */
    public void setObstacleHeight(float value) {
        this.obstacleHeight = value;
    }

    /**
     * Gets the value of the cloudFract property.
     * 
     */
    public float getCloudFract() {
        return cloudFract;
    }

    /**
     * Sets the value of the cloudFract property.
     * 
     */
    public void setCloudFract(float value) {
        this.cloudFract = value;
    }

    /**
     * Gets the value of the useCloudCover property.
     * 
     */
    public boolean isUseCloudCover() {
        return useCloudCover;
    }

    /**
     * Sets the value of the useCloudCover property.
     * 
     */
    public void setUseCloudCover(boolean value) {
        this.useCloudCover = value;
    }

}
