//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.23 at 06:20:10 PM EET 
//


package uk.ac.aber.simsphere;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlantType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlantType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://aber.ac.uk/simsphere}TemperatureRange"/>
 *         &lt;element name="MinStomatalResistance">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="10"/>
 *               &lt;maxInclusive value="500"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Beta">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="0.15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="B1">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="-0.5"/>
 *               &lt;maxInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="B2">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CriticalLeafWaterPot">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="5"/>
 *               &lt;maxInclusive value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CriticalSolarParam">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="25"/>
 *               &lt;maxInclusive value="300"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CuticleResistance">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="200"/>
 *               &lt;maxInclusive value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="StemResistance">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0.01"/>
 *               &lt;maxInclusive value="0.15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FractXylemPot">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FractStemResistance">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Rkocap">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Rccap">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Rzcap">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="InitialPlantWaterVol">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="0.1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Zstini">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="0.1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlantType", propOrder = {
    "temperatureRange",
    "minStomatalResistance",
    "beta",
    "b1",
    "b2",
    "criticalLeafWaterPot",
    "criticalSolarParam",
    "cuticleResistance",
    "stemResistance",
    "fractXylemPot",
    "fractStemResistance",
    "rkocap",
    "rccap",
    "rzcap",
    "initialPlantWaterVol",
    "zstini"
})
@XmlSeeAlso({
    Plant.class
})
public class PlantType {

    @XmlElement(name = "TemperatureRange", required = true)
    protected TemperatureRange temperatureRange;
    @XmlElement(name = "MinStomatalResistance")
    protected float minStomatalResistance;
    @XmlElement(name = "Beta")
    protected float beta;
    @XmlElement(name = "B1")
    protected float b1;
    @XmlElement(name = "B2")
    protected float b2;
    @XmlElement(name = "CriticalLeafWaterPot")
    protected float criticalLeafWaterPot;
    @XmlElement(name = "CriticalSolarParam")
    protected float criticalSolarParam;
    @XmlElement(name = "CuticleResistance")
    protected float cuticleResistance;
    @XmlElement(name = "StemResistance")
    protected float stemResistance;
    @XmlElement(name = "FractXylemPot")
    protected float fractXylemPot;
    @XmlElement(name = "FractStemResistance")
    protected float fractStemResistance;
    @XmlElement(name = "Rkocap")
    protected float rkocap;
    @XmlElement(name = "Rccap")
    protected float rccap;
    @XmlElement(name = "Rzcap")
    protected float rzcap;
    @XmlElement(name = "InitialPlantWaterVol")
    protected float initialPlantWaterVol;
    @XmlElement(name = "Zstini")
    protected float zstini;

    /**
     * Gets the value of the temperatureRange property.
     * 
     * @return
     *     possible object is
     *     {@link TemperatureRange }
     *     
     */
    public TemperatureRange getTemperatureRange() {
        return temperatureRange;
    }

    /**
     * Sets the value of the temperatureRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemperatureRange }
     *     
     */
    public void setTemperatureRange(TemperatureRange value) {
        this.temperatureRange = value;
    }

    /**
     * Gets the value of the minStomatalResistance property.
     * 
     */
    public float getMinStomatalResistance() {
        return minStomatalResistance;
    }

    /**
     * Sets the value of the minStomatalResistance property.
     * 
     */
    public void setMinStomatalResistance(float value) {
        this.minStomatalResistance = value;
    }

    /**
     * Gets the value of the beta property.
     * 
     */
    public float getBeta() {
        return beta;
    }

    /**
     * Sets the value of the beta property.
     * 
     */
    public void setBeta(float value) {
        this.beta = value;
    }

    /**
     * Gets the value of the b1 property.
     * 
     */
    public float getB1() {
        return b1;
    }

    /**
     * Sets the value of the b1 property.
     * 
     */
    public void setB1(float value) {
        this.b1 = value;
    }

    /**
     * Gets the value of the b2 property.
     * 
     */
    public float getB2() {
        return b2;
    }

    /**
     * Sets the value of the b2 property.
     * 
     */
    public void setB2(float value) {
        this.b2 = value;
    }

    /**
     * Gets the value of the criticalLeafWaterPot property.
     * 
     */
    public float getCriticalLeafWaterPot() {
        return criticalLeafWaterPot;
    }

    /**
     * Sets the value of the criticalLeafWaterPot property.
     * 
     */
    public void setCriticalLeafWaterPot(float value) {
        this.criticalLeafWaterPot = value;
    }

    /**
     * Gets the value of the criticalSolarParam property.
     * 
     */
    public float getCriticalSolarParam() {
        return criticalSolarParam;
    }

    /**
     * Sets the value of the criticalSolarParam property.
     * 
     */
    public void setCriticalSolarParam(float value) {
        this.criticalSolarParam = value;
    }

    /**
     * Gets the value of the cuticleResistance property.
     * 
     */
    public float getCuticleResistance() {
        return cuticleResistance;
    }

    /**
     * Sets the value of the cuticleResistance property.
     * 
     */
    public void setCuticleResistance(float value) {
        this.cuticleResistance = value;
    }

    /**
     * Gets the value of the stemResistance property.
     * 
     */
    public float getStemResistance() {
        return stemResistance;
    }

    /**
     * Sets the value of the stemResistance property.
     * 
     */
    public void setStemResistance(float value) {
        this.stemResistance = value;
    }

    /**
     * Gets the value of the fractXylemPot property.
     * 
     */
    public float getFractXylemPot() {
        return fractXylemPot;
    }

    /**
     * Sets the value of the fractXylemPot property.
     * 
     */
    public void setFractXylemPot(float value) {
        this.fractXylemPot = value;
    }

    /**
     * Gets the value of the fractStemResistance property.
     * 
     */
    public float getFractStemResistance() {
        return fractStemResistance;
    }

    /**
     * Sets the value of the fractStemResistance property.
     * 
     */
    public void setFractStemResistance(float value) {
        this.fractStemResistance = value;
    }

    /**
     * Gets the value of the rkocap property.
     * 
     */
    public float getRkocap() {
        return rkocap;
    }

    /**
     * Sets the value of the rkocap property.
     * 
     */
    public void setRkocap(float value) {
        this.rkocap = value;
    }

    /**
     * Gets the value of the rccap property.
     * 
     */
    public float getRccap() {
        return rccap;
    }

    /**
     * Sets the value of the rccap property.
     * 
     */
    public void setRccap(float value) {
        this.rccap = value;
    }

    /**
     * Gets the value of the rzcap property.
     * 
     */
    public float getRzcap() {
        return rzcap;
    }

    /**
     * Sets the value of the rzcap property.
     * 
     */
    public void setRzcap(float value) {
        this.rzcap = value;
    }

    /**
     * Gets the value of the initialPlantWaterVol property.
     * 
     */
    public float getInitialPlantWaterVol() {
        return initialPlantWaterVol;
    }

    /**
     * Sets the value of the initialPlantWaterVol property.
     * 
     */
    public void setInitialPlantWaterVol(float value) {
        this.initialPlantWaterVol = value;
    }

    /**
     * Gets the value of the zstini property.
     * 
     */
    public float getZstini() {
        return zstini;
    }

    /**
     * Sets the value of the zstini property.
     * 
     */
    public void setZstini(float value) {
        this.zstini = value;
    }

}
