//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.23 at 06:20:10 PM EET 
//


package uk.ac.aber.simsphere;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://aber.ac.uk/simsphere}Overpass"/>
 *         &lt;element ref="{http://aber.ac.uk/simsphere}Vegetation"/>
 *         &lt;element ref="{http://aber.ac.uk/simsphere}Surface"/>
 *         &lt;element ref="{http://aber.ac.uk/simsphere}Meteorological"/>
 *         &lt;element ref="{http://aber.ac.uk/simsphere}Plants"/>
 *         &lt;element ref="{http://aber.ac.uk/simsphere}Soils"/>
 *         &lt;element ref="{http://aber.ac.uk/simsphere}SoundingSet"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "overpass",
    "vegetation",
    "surface",
    "meteorological",
    "plants",
    "soils",
    "soundingSet"
})
@XmlRootElement(name = "Simsphere")
public class Simsphere {

    @XmlElement(name = "Overpass", required = true)
    protected Overpass overpass;
    @XmlElement(name = "Vegetation", required = true)
    protected Vegetation vegetation;
    @XmlElement(name = "Surface", required = true)
    protected Surface surface;
    @XmlElement(name = "Meteorological", required = true)
    protected Meteorological meteorological;
    @XmlElement(name = "Plants", required = true)
    protected Plants plants;
    @XmlElement(name = "Soils", required = true)
    protected Soils soils;
    @XmlElement(name = "SoundingSet", required = true)
    protected SoundingSet soundingSet;

    /**
     * Gets the value of the overpass property.
     * 
     * @return
     *     possible object is
     *     {@link Overpass }
     *     
     */
    public Overpass getOverpass() {
        return overpass;
    }

    /**
     * Sets the value of the overpass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Overpass }
     *     
     */
    public void setOverpass(Overpass value) {
        this.overpass = value;
    }

    /**
     * Gets the value of the vegetation property.
     * 
     * @return
     *     possible object is
     *     {@link Vegetation }
     *     
     */
    public Vegetation getVegetation() {
        return vegetation;
    }

    /**
     * Sets the value of the vegetation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vegetation }
     *     
     */
    public void setVegetation(Vegetation value) {
        this.vegetation = value;
    }

    /**
     * Gets the value of the surface property.
     * 
     * @return
     *     possible object is
     *     {@link Surface }
     *     
     */
    public Surface getSurface() {
        return surface;
    }

    /**
     * Sets the value of the surface property.
     * 
     * @param value
     *     allowed object is
     *     {@link Surface }
     *     
     */
    public void setSurface(Surface value) {
        this.surface = value;
    }

    /**
     * Gets the value of the meteorological property.
     * 
     * @return
     *     possible object is
     *     {@link Meteorological }
     *     
     */
    public Meteorological getMeteorological() {
        return meteorological;
    }

    /**
     * Sets the value of the meteorological property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meteorological }
     *     
     */
    public void setMeteorological(Meteorological value) {
        this.meteorological = value;
    }

    /**
     * Gets the value of the plants property.
     * 
     * @return
     *     possible object is
     *     {@link Plants }
     *     
     */
    public Plants getPlants() {
        return plants;
    }

    /**
     * Sets the value of the plants property.
     * 
     * @param value
     *     allowed object is
     *     {@link Plants }
     *     
     */
    public void setPlants(Plants value) {
        this.plants = value;
    }

    /**
     * Gets the value of the soils property.
     * 
     * @return
     *     possible object is
     *     {@link Soils }
     *     
     */
    public Soils getSoils() {
        return soils;
    }

    /**
     * Sets the value of the soils property.
     * 
     * @param value
     *     allowed object is
     *     {@link Soils }
     *     
     */
    public void setSoils(Soils value) {
        this.soils = value;
    }

    /**
     * Gets the value of the soundingSet property.
     * 
     * @return
     *     possible object is
     *     {@link SoundingSet }
     *     
     */
    public SoundingSet getSoundingSet() {
        return soundingSet;
    }

    /**
     * Sets the value of the soundingSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoundingSet }
     *     
     */
    public void setSoundingSet(SoundingSet value) {
        this.soundingSet = value;
    }

}
