//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.10 at 03:01:39 PM EET 
//


package uk.ac.aber.simsphere;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RKS">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CosbyB">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="2"/>
 *               &lt;maxInclusive value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="THMax">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0.3"/>
 *               &lt;maxInclusive value="0.5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Psi">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rks",
    "cosbyB",
    "thMax",
    "psi"
})
@XmlRootElement(name = "Soil")
public class Soil {

    @XmlElement(name = "RKS")
    protected float rks;
    @XmlElement(name = "CosbyB")
    protected float cosbyB;
    @XmlElement(name = "THMax")
    protected float thMax;
    @XmlElement(name = "Psi")
    protected float psi;
    @XmlAttribute(name = "ID")
    protected String id;

    /**
     * Gets the value of the rks property.
     * 
     */
    public float getRKS() {
        return rks;
    }

    /**
     * Sets the value of the rks property.
     * 
     */
    public void setRKS(float value) {
        this.rks = value;
    }

    /**
     * Gets the value of the cosbyB property.
     * 
     */
    public float getCosbyB() {
        return cosbyB;
    }

    /**
     * Sets the value of the cosbyB property.
     * 
     */
    public void setCosbyB(float value) {
        this.cosbyB = value;
    }

    /**
     * Gets the value of the thMax property.
     * 
     */
    public float getTHMax() {
        return thMax;
    }

    /**
     * Sets the value of the thMax property.
     * 
     */
    public void setTHMax(float value) {
        this.thMax = value;
    }

    /**
     * Gets the value of the psi property.
     * 
     */
    public float getPsi() {
        return psi;
    }

    /**
     * Sets the value of the psi property.
     * 
     */
    public void setPsi(float value) {
        this.psi = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
