//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.10 at 10:39:31 AM EET 
//


package uk.ac.aber.simsphere;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FractVegCover">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LeafAreaIndex">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FoliageAlbedo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FoliageEmissivity">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://aber.ac.uk/simsphere>FoliageEmissivityType">
 *                 &lt;attribute name="calculate" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CI">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="110"/>
 *               &lt;maxInclusive value="400"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CO">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="250"/>
 *               &lt;maxInclusive value="710"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SurfOzoneConcentration">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="0.25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AirOzoneConcentration">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="0.25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fractVegCover",
    "leafAreaIndex",
    "foliageAlbedo",
    "foliageEmissivity",
    "ci",
    "co",
    "surfOzoneConcentration",
    "airOzoneConcentration"
})
@XmlRootElement(name = "VegCommon")
public class VegCommon {

    @XmlElement(name = "FractVegCover")
    protected float fractVegCover;
    @XmlElement(name = "LeafAreaIndex")
    protected float leafAreaIndex;
    @XmlElement(name = "FoliageAlbedo")
    protected float foliageAlbedo;
    @XmlElement(name = "FoliageEmissivity", required = true)
    protected VegCommon.FoliageEmissivity foliageEmissivity;
    @XmlElement(name = "CI")
    protected float ci;
    @XmlElement(name = "CO")
    protected float co;
    @XmlElement(name = "SurfOzoneConcentration")
    protected float surfOzoneConcentration;
    @XmlElement(name = "AirOzoneConcentration")
    protected float airOzoneConcentration;

    /**
     * Gets the value of the fractVegCover property.
     * 
     */
    public float getFractVegCover() {
        return fractVegCover;
    }

    /**
     * Sets the value of the fractVegCover property.
     * 
     */
    public void setFractVegCover(float value) {
        this.fractVegCover = value;
    }

    /**
     * Gets the value of the leafAreaIndex property.
     * 
     */
    public float getLeafAreaIndex() {
        return leafAreaIndex;
    }

    /**
     * Sets the value of the leafAreaIndex property.
     * 
     */
    public void setLeafAreaIndex(float value) {
        this.leafAreaIndex = value;
    }

    /**
     * Gets the value of the foliageAlbedo property.
     * 
     */
    public float getFoliageAlbedo() {
        return foliageAlbedo;
    }

    /**
     * Sets the value of the foliageAlbedo property.
     * 
     */
    public void setFoliageAlbedo(float value) {
        this.foliageAlbedo = value;
    }

    /**
     * Gets the value of the foliageEmissivity property.
     * 
     * @return
     *     possible object is
     *     {@link VegCommon.FoliageEmissivity }
     *     
     */
    public VegCommon.FoliageEmissivity getFoliageEmissivity() {
        return foliageEmissivity;
    }

    /**
     * Sets the value of the foliageEmissivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link VegCommon.FoliageEmissivity }
     *     
     */
    public void setFoliageEmissivity(VegCommon.FoliageEmissivity value) {
        this.foliageEmissivity = value;
    }

    /**
     * Gets the value of the ci property.
     * 
     */
    public float getCI() {
        return ci;
    }

    /**
     * Sets the value of the ci property.
     * 
     */
    public void setCI(float value) {
        this.ci = value;
    }

    /**
     * Gets the value of the co property.
     * 
     */
    public float getCO() {
        return co;
    }

    /**
     * Sets the value of the co property.
     * 
     */
    public void setCO(float value) {
        this.co = value;
    }

    /**
     * Gets the value of the surfOzoneConcentration property.
     * 
     */
    public float getSurfOzoneConcentration() {
        return surfOzoneConcentration;
    }

    /**
     * Sets the value of the surfOzoneConcentration property.
     * 
     */
    public void setSurfOzoneConcentration(float value) {
        this.surfOzoneConcentration = value;
    }

    /**
     * Gets the value of the airOzoneConcentration property.
     * 
     */
    public float getAirOzoneConcentration() {
        return airOzoneConcentration;
    }

    /**
     * Sets the value of the airOzoneConcentration property.
     * 
     */
    public void setAirOzoneConcentration(float value) {
        this.airOzoneConcentration = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://aber.ac.uk/simsphere>FoliageEmissivityType">
     *       &lt;attribute name="calculate" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class FoliageEmissivity {

        @XmlValue
        protected float value;
        @XmlAttribute(name = "calculate", required = true)
        protected boolean calculate;

        /**
         * Gets the value of the value property.
         * 
         */
        public float getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(float value) {
            this.value = value;
        }

        /**
         * Gets the value of the calculate property.
         * 
         */
        public boolean isCalculate() {
            return calculate;
        }

        /**
         * Sets the value of the calculate property.
         * 
         */
        public void setCalculate(boolean value) {
            this.calculate = value;
        }

    }

}
